task: binary_classification

dataset_parameters:
  inputs: image_filename
  targets: binary_encoded_label
  tile_size: 256
  n_tiles: 4

model_parameters:
  model_class: MultiInstanceLearningModel
  model_args:
    n_instances: 2
    model_module: timm
    model_name: resnet18
    pretrained: True
    head_args:
      intermediate_features: 512
      n_classes: 1
      pooling_type: avg
      activation: ReLU
      activation_args: {}
      dropout_probability: 0
  model_checkpoint_path: null

training_parameters:
  folds: [fold1, fold2, fold3, fold4, fold5]
  loss_function: BCEWithLogitsLoss
  loss_args: {}
  optimizer: AdamW
  optimizer_args:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0
  lr_scheduler: StepLR
  lr_scheduler_args:
    factor: 0.5
    patience: 5
  epochs: 250
  early_stopping_patience: 5
  training_batch_size: 16
  test_batch_size: 32
  num_workers: 4
  random_state: 42
  deterministic_cudnn: False
  device: cuda

transform_parameters:
  horizontal_flip_probability: 0.5
  vertical_flip_probability: 0.5
  normalize_mean: [0.2731810965836966, 0.27189342403255906, 0.27162518728784174]
  normalize_std: [0.44413230484960264, 0.44217890756782346, 0.4434057723960932]
  normalize_max_pixel_value: 255

inference_parameters:
  folds: [fold1, fold2, fold3, fold4, fold5]

persistence_parameters:
  name: mil_model
  visualize_learning_curve: True
  visualize_training_scores: True
  save_best_model: True
  save_epoch_model: []